/**
 * Collateral Management with Firebase Storage
 * Handles secure file uploads with signed URLs
 */

import { ref, uploadBytes, getDownloadURL, getMetadata, deleteObject } from 'firebase/storage';
import { storage } from './config';
import { isDemoMode } from './config';

export interface CollateralFile {
  file: File;
  type: 'image' | 'document' | 'pdf';
  description?: string;
}

export interface UploadedFile {
  url: string;
  thumbnailUrl?: string;
  path: string;
  size: number;
  contentType: string;
  uploadedAt: Date;
  metadata?: {
    originalName: string;
    description?: string;
  };
}

/**
 * Upload collateral image with secure storage
 * Returns signed URL for access
 */
export async function uploadCollateralFile(
  agencyId: string,
  collateralId: string,
  fileData: CollateralFile
): Promise<UploadedFile> {
  if (isDemoMode) {
    return {
      url: `https://demo-storage.example.com/collateral/${fileData.file.name}`,
      path: `collateral/${fileData.file.name}`,
      size: fileData.file.size,
      contentType: fileData.file.type,
      uploadedAt: new Date(),
      metadata: {
        originalName: fileData.file.name,
        description: fileData.description,
      },
    };
  }

  try {
    const fileExt = fileData.file.name.split('.').pop();
    const timestamp = Date.now();
    const fileName = `${fileData.type}-${timestamp}.${fileExt}`;
    const path = `agencies/${agencyId}/collateral/${collateralId}/${fileName}`;

    // Upload file (private by default)
    const storageRef = ref(storage, path);
    await uploadBytes(storageRef, fileData.file, {
      contentType: fileData.file.type,
      customMetadata: {
        originalName: fileData.file.name,
        description: fileData.description || '',
        type: fileData.type,
        collateralId,
        agencyId,
      },
    });

    // Get download URL (signed URL for private files)
    const url = await getDownloadURL(storageRef);

    // Check if thumbnail exists (generated by Cloud Function)
    let thumbnailUrl: string | undefined;
    try {
      const thumbPath = path.replace(/(\.[^.]+)$/, '_thumb$1');
      const thumbRef = ref(storage, thumbPath);
      thumbnailUrl = await getDownloadURL(thumbRef);
    } catch {
      // Thumbnail not generated yet, will be available later
    }

    // Get file metadata
    const metadata = await getMetadata(storageRef);

    return {
      url,
      thumbnailUrl,
      path,
      size: fileData.file.size,
      contentType: fileData.file.type,
      uploadedAt: new Date(),
      metadata: {
        originalName: fileData.file.name,
        description: fileData.description,
      },
    };
  } catch (error: any) {
    console.error('Error uploading collateral file:', error);
    throw new Error(`Failed to upload file: ${error.message}`);
  }
}

/**
 * Get signed URL for collateral file (temporary access)
 */
export async function getSignedUrl(
  filePath: string,
  expiresIn: number = 3600 // 1 hour default
): Promise<string> {
  if (isDemoMode) {
    return `https://demo-storage.example.com/${filePath}`;
  }

  try {
    const storageRef = ref(storage, filePath);
    // Note: In production, you'd use a Cloud Function to generate signed URLs
    // For now, using getDownloadURL which works for public files
    // For private files, implement a Cloud Function
    return await getDownloadURL(storageRef);
  } catch (error: any) {
    console.error('Error getting signed URL:', error);
    throw new Error(`Failed to get file URL: ${error.message}`);
  }
}

/**
 * Delete collateral file
 */
export async function deleteCollateralFile(filePath: string): Promise<void> {
  if (isDemoMode) return;

  try {
    const storageRef = ref(storage, filePath);
    await deleteObject(storageRef);

    // Also try to delete thumbnail if exists
    try {
      const thumbPath = filePath.replace(/(\.[^.]+)$/, '_thumb$1');
      const thumbRef = ref(storage, thumbPath);
      await deleteObject(thumbRef);
    } catch {
      // Thumbnail doesn't exist, ignore
    }
  } catch (error: any) {
    console.error('Error deleting collateral file:', error);
    throw new Error(`Failed to delete file: ${error.message}`);
  }
}

/**
 * Upload multiple collateral files
 */
export async function uploadMultipleCollateralFiles(
  agencyId: string,
  collateralId: string,
  files: CollateralFile[]
): Promise<UploadedFile[]> {
  const uploadPromises = files.map(file => 
    uploadCollateralFile(agencyId, collateralId, file)
  );
  
  return Promise.all(uploadPromises);
}

